#pragma once

#include "types.h"

#define PINB        (volatile uint8 *) 0x23
#define DDRB        (volatile uint8 *) 0x24
#define PORTB       (volatile uint8 *) 0x25
#define PINC        (volatile uint8 *) 0x26
#define DDRC        (volatile uint8 *) 0x27
#define PORTC       (volatile uint8 *) 0x28
#define PIND        (volatile uint8 *) 0x29
#define DDRD        (volatile uint8 *) 0x2A
#define PORTD       (volatile uint8 *) 0x2B
#define TIFR0       (volatile uint8 *) 0x35
#define TIFR1       (volatile uint8 *) 0x36
#define TIFR2       (volatile uint8 *) 0x37
#define PCIFR       (volatile uint8 *) 0x3B
#define EIFR        (volatile uint8 *) 0x3C
#define EIMSK       (volatile uint8 *) 0x3D
#define GPIOR0      (volatile uint8 *) 0x3E
#define EECR        (volatile uint8 *) 0x3F
#define EEDR        (volatile uint8 *) 0x40
#define EEARL       (volatile uint8 *) 0x41
#define EEARH       (volatile uint8 *) 0x42
#define GTCCR       (volatile uint8 *) 0x43
#define TCCR0A      (volatile uint8 *) 0x44
#define TCCR0B      (volatile uint8 *) 0x45
#define TCNT0       (volatile uint8 *) 0x46
#define OCR0A       (volatile uint8 *) 0x47
#define OCR0B       (volatile uint8 *) 0x48
#define GPIOR1      (volatile uint8 *) 0x4A
#define GPIOR2      (volatile uint8 *) 0x4B
#define SPCR        (volatile uint8 *) 0x4C
#define SPSR        (volatile uint8 *) 0x4D
#define SPDR        (volatile uint8 *) 0x4E
#define ACSR        (volatile uint8 *) 0x50
#define SMCR        (volatile uint8 *) 0x53
#define MCUSR       (volatile uint8 *) 0x54
#define MCUCR       (volatile uint8 *) 0x55
#define SPMCSR      (volatile uint8 *) 0x57
#define SPL         (volatile uint8 *) 0x5D
#define SPH         (volatile uint8 *) 0x5E
#define SREG        (volatile uint8 *) 0x5F
#define WDTCSR      (volatile uint8 *) 0x60
#define CLKPR       (volatile uint8 *) 0x61
#define PRR         (volatile uint8 *) 0x64
#define OSCCAL      (volatile uint8 *) 0x66
#define PCICR       (volatile uint8 *) 0x68
#define EICRA       (volatile uint8 *) 0x69
#define PCMSK0      (volatile uint8 *) 0x6B
#define PCMSK1      (volatile uint8 *) 0x6C
#define PCMSK2      (volatile uint8 *) 0x6D
#define TIMSK0      (volatile uint8 *) 0x6E
#define TIMSK1      (volatile uint8 *) 0x6F
#define TIMSK2      (volatile uint8 *) 0x70
#define ADCL        (volatile uint8 *) 0x78
#define ADCH        (volatile uint8 *) 0x79
#define ADCSRA      (volatile uint8 *) 0x7A
#define ADCSRB      (volatile uint8 *) 0x7B
#define ADMUX       (volatile uint8 *) 0x7C
#define DIDR0       (volatile uint8 *) 0x7E
#define DIDR1       (volatile uint8 *) 0x7F
#define TCCR1A      (volatile uint8 *) 0x80
#define TCCR1B      (volatile uint8 *) 0x81
#define TCCR1C      (volatile uint8 *) 0x82
#define TCNT1L      (volatile uint8 *) 0x84
#define TCNT1H      (volatile uint8 *) 0x85
#define ICR1L       (volatile uint8 *) 0x86
#define ICR1H       (volatile uint8 *) 0x87
#define OCR1AL      (volatile uint8 *) 0x88
#define OCR1AH      (volatile uint8 *) 0x89
#define OCR1BL      (volatile uint8 *) 0x8A
#define OCR1BH      (volatile uint8 *) 0x8B
#define TCCR2A      (volatile uint8 *) 0xB0
#define TCCR2B      (volatile uint8 *) 0xB1
#define TCNT2       (volatile uint8 *) 0xB2
#define OCR2A       (volatile uint8 *) 0xB3
#define OCR2B       (volatile uint8 *) 0xB4
#define ASSR        (volatile uint8 *) 0xB6
#define TWBR        (volatile uint8 *) 0xB8
#define TWSR        (volatile uint8 *) 0xB9
#define TWAR        (volatile uint8 *) 0xBA
#define TWDR        (volatile uint8 *) 0xBB
#define TWCR        (volatile uint8 *) 0xBC
#define TWAMR       (volatile uint8 *) 0xBD
#define UCSR0A      (volatile uint8 *) 0xC0
#define UCSR0B      (volatile uint8 *) 0xC1
#define UCSR0C      (volatile uint8 *) 0xC2
#define UBRR0L      (volatile uint8 *) 0xC4
#define UBRR0H      (volatile uint8 *) 0xC5
#define UDR0        (volatile uint8 *) 0xC6